### ISSUE TITLE
pint roadmap

### ISSUE THREAD

**Issue by fuwaa** [fuwaa/pint#12]
#### `🚀 Complete` Refactoring Gitccentify
- [x] Base Brand Redesign
- [x] Base Popup UI Redesign
- [x] Implement main functionality (Get Set)

#### `🚀 Complete` QuickScheme Implementation 
- [x] Implement accent color scheme generator
- [x] fix quck change color scheme gen
- [x] add hex setting override in quick change
- [x] Add a text color switch for the doozeys who's crazy enough to use light mode

#### `🕒 Todo` Predefined Color Schemes
- [x] Implement colorscheme feature
- [ ] Github Dark
- [ ] Github Light
- [ ] Solarized Dark
- [ ] #35

####  `🕒 Todo` Advanced Customisation
- [x] Implement options UI base
- [ ] Implement options ui group based
- [x] Implement options ui advanced (full customisation)

####  `🕒 Todo` Global Pints Implementation
- [ ] #36
- [ ] implement global pints (possibly via github dotfiles? or should i use my own framework?)

####  `🕒 Todo` Code Quality
- [x] Refactor QuickScheme
- [ ] Refactor Pint Code because I suck at using typescript
- [ ] Fix DeepSource Issues
- [ ] Fix Linting Issues
- [x] yeet the old code

#### `🕒 Todo` Branding/Marketing
- [ ] Create a website for Pint

#### `🕒 Todo` Documentation
- [ ] Add comments to code
- [ ] Update README

####  `🕒 Todo` QOL
- [ ] Add extension install page
- [ ] Port to Mozilla Firefox

####  `🕒 Todo` Release
- [ ] Update chrome extension page
- [ ] Update chrome extension itself

####  `🕒 Todo` Bugfixing:
- [ ] Inconsistent padding
- [x] ~~Color preview is broken on QuickScheme~~ Fixed via #28
> Bug Comment:
> <i>~~Removed on #11~~</i>
> <i>Planned to reimplement due to new color scheming changes in #27</i>
- [x] ~~QuickScheme hex override does not work if no hashtag is supplied~~ Fixed via #22
- [x] ~~Options UI crashes when using paint tool. (probably related to paint tool)~~ Fixed via #22
- [x] ~~Color picker not using grabbed value~~ It's not a bug, it's a feature via #22
> Bug Comment:
> <i>~~Nah it was better to use decafbad as a meme lmao~~</i>
> <i>Nah c0ffee is better.</i>
- [x] ~~Quirk: You need to add a # to set it properly.~~ Fixed via #24 
- [x] ~~header bug (to be fixed in next pr)~~ Fixed via #27 
theres more in the backlog but this is the bare minimum before i can open contributions and push a release :)

**Comment by fuwaa** [comment]
URGENT todo: 
- [ ] fix opacityGroup.js
- [ ] fix opacityHelper.js
- [ ] fix colorScales.js

**Comment by fuwaa** [comment]
closed in favor of spread issues making it easier to read.
